# Generated by Django 5.1 on 2024-09-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_contactus_product_in_stock_cart_cartproduct_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='subject',
        ),
    ]
