# Generated by Django 5.1 on 2024-09-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_remove_comment_rating_alter_comment_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='comment',
        ),
    ]
